/**********************************************************************
-  File name : SYS.H
-  Author : yueling_liu	Version: 0.1	Date: 2018年10月01日星期一
-  Description :System Global File
-  Function :主要存放51寄存器，主频，全局参数等 
-  History :	
   1.Date: ...
     Author: ...
	 Modification: ...
   2. ...
**********************************************************************/

#ifndef __SYS_H_
#define __SYS_H_

//--Header File--//
#include "STC15.h"
#include "typint.h"
#include "intrins.h"
#include "stdio.h"
#include "intrins.h"
//#include "uart.h"


//--Type Definition--//

//--Extern Variable--//

//--Definition--//
//#define FOSC	11059200L



//--Interface--//

//--Function Prototype--//

#endif
